### ISSUE TITLE
doesnt work (output)

### ISSUE THREAD

**Issue by miqumi** [OpenAsar/arrpc#41]
```
C:\Users\miqumi\arrpc>node src
(node:3012) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3012) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
[arRPC] arRPC v3.1.0
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::1337
    at Server.setupListenHandle [as _listen2] (node:net:1872:16)
    at listenInCluster (node:net:1920:12)
    at Server.listen (node:net:2008:7)
    at new WebSocketServer (C:\Users\miqumi\arrpc\node_modules\ws\lib\websocket-server.js:97:20)
    at file:///C:/Users/miqumi/arrpc/src/bridge.js:14:13
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async DefaultModuleLoader.import (node:internal/modules/esm/loader:228:24)
    at async loadESM (node:internal/process/esm_loader:40:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)
Emitted 'error' event on WebSocketServer instance at:
    at Server.emit (node:events:514:28)
    at emitErrorNT (node:net:1899:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 1337
}

Node.js v20.5.0

```

**Comment by CanadaHonk** [comment]
Please use [the Discord server](https://discord.com/invite/neMncS2) for support, not GitHub issues for easier communication.
