### ISSUE TITLE
discord sublime rpc error / on ipc too

### ISSUE THREAD

**Issue by xkxl2x0** [OpenAsar/arrpc#44]
give me this error when i run the Discord sublime rpc 
[arRPC > ipc] error whilst reading Error: failed reading data
    at read (file:///C:/Users/tws/arrpc/src/transports/ipc.js:62:20)
    at Socket.<anonymous> (file:///C:/Users/tws/arrpc/src/transports/ipc.js:183:9)
    at Socket.emit (node:events:513:28)
    at emitReadable_ (node:internal/streams/readable:590:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)

**Comment by CanadaHonk** [comment]
Use [the Discord server](https://discord.com/invite/neMncS2) for support, not GitHub issues.
