### ISSUE TITLE
ReferenceError: fetch is not defined 

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [OpenAsar/arrpc#7]
```
[arRPC > ipc] new connection!
[arRPC > ipc] handshake: { v: 1, client_id: '568815339807309834' }
[arRPC > ipc] sending { cmd: 'DISPATCH', evt: 'READY', data: { v: 1 } }
[arRPC > ipc] message {
  args: {
    pid: 18106,
    activity: {
      buttons: [Array],
      state: 'Idling',
      details: 'Main Menu',
      timestamps: [Object],
      assets: [Object],
      instance: false
    }
  },
  cmd: 'SET_ACTIVITY',
  nonce: '1'
}
file:///home/pm/Documents/arrpc/src/server.js:40
          socket.application = await (await fetch(`https://discord.com/api/v9/oauth2/applications/${socket.clientId}/rpc`)).json();
                                      ^

ReferenceError: fetch is not defined
    at RPCServer.onMessage (file:///home/pm/Documents/arrpc/src/server.js:40:39)
    at IPCServer.onMessage (file:///home/pm/Documents/arrpc/src/transports/ipc.js:241:10)
    at Socket.emit (node:events:520:28)
    at read (file:///home/pm/Documents/arrpc/src/transports/ipc.js:86:14)
    at Socket.<anonymous> (file:///home/pm/Documents/arrpc/src/transports/ipc.js:184:9)
    at Socket.emit (node:events:520:28)
    at emitReadable_ (node:internal/streams/readable:578:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```
*I'm not tech-savy to know if that error message is just due to a miss-configuration or just one of the features not yet implemented*
Tried natively on Linux, with Ryujinx with a modified arrpc Discord stable client, with Vencord installed.

**Comment by CanadaHonk** [comment]
Update arRPC + need to use Node >=18 as said in readme ;)
